### ISSUE TITLE
Windows CI

### ISSUE THREAD

**Issue by rracariu** [LightBender/SecureD#16]
ATM this package is not tested on Windows and there are build issues because of typos and missing imports, see https://github.com/LightBender/SecureD/pull/14
Also, it doesn't build for Win32 with dmd and ldc https://github.com/LightBender/SecureD/issues/15.

Windows CI would catch all this issues and prevent regressions. Would be great to add Azure Pipelines, some inspiration https://github.com/ldc-developers/ldc/pull/2998.

Ideally the Windows CI should target dmd 32/64bit and ldc 32/64bit.

**Comment by LightBender** [comment]
The Travis CI is broken because they took away the free tier and I cannot afford to pay for builds on this project. However, the most recent version (2.0.3) was built on Windows (my primary devbox) so it should fix your issues.
