### ISSUE TITLE
Provide easy to reach docs

### ISSUE THREAD

**Issue by wilzbach** [LightBender/SecureD#5]
It would be very helpful if your README contains a couple of high-level usage examples, s.t. a user doesn't have to go through the code ;-)

Ideally the README would also contain the most important API details, s.t. your package can be used without looking at the code.

So just [as you made the case for excellent APIs](http://forum.dlang.org/post/o3l87g$aoi$1@digitalmars.com), there's another one for good documentation ;-)

Selected examples from the D community:

- README based: https://github.com/ikod/dlang-requests
- Adapted dlang.org (Example: http://docs.random.dlang.io/latest/index.html)
- [ScoD](Example: http://martinnowak.github.io/bloom/bloom.html
- [adrdox](https://github.com/adamdruppe/adrdox)

See also: https://wiki.dlang.org/Documentation_Generators

**Comment by LightBender** [comment]
I added some examples to the README with this comment: https://github.com/LightBender/SecureD/commit/021eba633d03b24da37fdc75ba8383d9775fc5b4

**Comment by wilzbach** [comment]
Nice!. Thanks a lot!
Btw how about using some default key (e.g. `"the quick brown fox jumps over the lazy dog"` seems to be popular) instead of `[ 0x01 //rest of key ];` as it allows easy copy & paste to try it out?

**Comment by LightBender** [comment]
Good feedback. I've pushed this: https://github.com/LightBender/SecureD/commit/50ce91cb4cd630bf757d7bc1e2d5297499aab9fc Which should resolve this issue
