### ISSUE TITLE
Would this work with LibreSSL?

### ISSUE THREAD

**Issue by drosehn** [LightBender/SecureD#6]
Do you know if this could be hooked up to use LibreSSL instead of OpenSSL?

(disclaimer: I haven't done much with D-lang, but I keep watching all the YouTube videos 😄  )

**Comment by LightBender** [comment]
IIRC LibreSSL is API compatible, so it should just be as simple as pointing the linker at the LibreSSL library file. I haven't tested it though. Even if it isn't though, a Pull Request would be as simple as using version(LibreSSL) to point to the LibreSSL methods and defining a build configuration as shown in dub.json.
